server:
  port: 8081

spring:
  application:
    name: bot

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://72.60.173.101:33307/movetedatabase}
    username: ${SPRING_DATASOURCE_USERNAME:mysql}
    password: ${SPRING_DATASOURCE_PASSWORD:ltm8d5vwazdvrsbt}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      auto-commit: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

app:
  request:
    mapping: api/back-whatsapp-qr-app
  version: '@project.version@'
  url:
    services:
      products-service: ${PRODUCTS_SERVICE_URL:https://gfvsgktksbutb3pdokevf6vhbi.apigateway.us-phoenix-1.oci.customer-oci.com/arq-prd-v3/}
  default-product-image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAIAAACx0UUt...

cloudinary:
  cloud:
    name: ${CLOUDINARY_CLOUD_NAME:dfotyo6jc}
  api:
    key: ${CLOUDINARY_API_KEY:341545146697844}
    secret: ${CLOUDINARY_API_SECRET:PvB8b7BMSd0lihsjuMeLImEsbz4}

landing:
  page:
    url: ${LANDING_PAGE_URL:https://qr-movete.is.arqbs.com}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    io:
      jsonwebtoken: DEBUG
    com:
      fasterxml:
        jackson: DEBUG
      restaurante:
        bot: DEBUG

