server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bot
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://72.60.173.101:33307/movetedatabase}
    username: ${SPRING_R2DBC_USERNAME:mysql}
    password: ${SPRING_R2DBC_PASSWORD:ltm8d5vwazdvrsbt}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

app:
  request:
    mapping: api/back-whatsapp-qr-app
  version: '@version@'
  url:
    services:
      products-service: ${PRODUCTS_SERVICE_URL:https://gfvsgktksbutb3pdokevf6vhbi.apigateway.us-phoenix-1.oci.customer-oci.com/arq-prd-v3/}
  default-product-image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAIAAACx0UUt...

cloudinary:
  cloud:
    name: ${CLOUDINARY_CLOUD_NAME:dfotyo6jc}
  api:
    key: ${CLOUDINARY_API_KEY:341545146697844}
    secret: ${CLOUDINARY_API_SECRET:PvB8b7BMSd0lihsjuMeLImEsbz4}

landing:
  page:
    url: ${LANDING_PAGE_URL:https://qr-movete.is.arqbs.com}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        r2dbc: DEBUG
    io:
      jsonwebtoken: DEBUG
      r2dbc: DEBUG
    com:
      fasterxml:
        jackson: DEBUG
      restaurante:
        bot: DEBUG
